ALTER TABLE TSSales MODIFY COLUMN TrackingNumber VARCHAR(10);
ALTER TABLE TSSales ADD CONSTRAINT sales_PK PRIMARY KEY (TrackingNumber);

ALTER TABLE TSInventorySales MODIFY COLUMN TrackingNumber VARCHAR(10), MODIFY COLUMN MaterialCode VARCHAR(12);
ALTER TABLE TSInventorySales ADD CONSTRAINT invsales_PK PRIMARY KEY (TrackingNumber,MaterialCode);

ALTER TABLE TSInventory MODIFY COLUMN MaterialCode VARCHAR(12);
ALTER TABLE TSInventory ADD CONSTRAINT inv_PK PRIMARY KEY (MaterialCode);

ALTER TABLE TSCost MODIFY COLUMN MaterialCode VARCHAR(12);
ALTER TABLE TSCost ADD CONSTRAINT cost_PK PRIMARY KEY (MaterialCode);

ALTER TABLE TSCustomers ADD CONSTRAINT cust_PK PRIMARY KEY (CustomerCode,CompanyID);

ALTER TABLE TSCustomerAddress MODIFY COLUMN CustomerAddress VARCHAR(250);
ALTER TABLE TSCustomerAddress ADD CONSTRAINT add_PK PRIMARY KEY (CustomerCode,CustomerAddress);

ALTER TABLE TSCustomerPhone MODIFY COLUMN CustomerPhone INT(12), MODIFY COLUMN CustomerFAX INT(12);
ALTER TABLE TSCustomerPhone ADD CONSTRAINT ph_PK PRIMARY KEY (CustomerCode,CustomerPhone,CustomerFAX);